// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-2t5GssS3TtbkOdLhkhAPAnnotm0goY',
    appId: '1:158681002300:web:3fb4927d3c8b69e1efee39',
    messagingSenderId: '158681002300',
    projectId: 'zinc-primer-455711-p7',
    authDomain: 'zinc-primer-455711-p7.firebaseapp.com',
    storageBucket: 'zinc-primer-455711-p7.firebasestorage.app',
    measurementId: 'G-XW0SGGXXYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXuulA43U6x1AZdKAFyop3B0WpbjPZn4',
    appId: '1:158681002300:android:fb9307239b7e343aefee39',
    messagingSenderId: '158681002300',
    projectId: 'zinc-primer-455711-p7',
    storageBucket: 'zinc-primer-455711-p7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwWq7xyYE77M5D9xiuDWtQm9CD-wVtOnQ',
    appId: '1:158681002300:ios:d3f671dfc2bd742fefee39',
    messagingSenderId: '158681002300',
    projectId: 'zinc-primer-455711-p7',
    storageBucket: 'zinc-primer-455711-p7.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwWq7xyYE77M5D9xiuDWtQm9CD-wVtOnQ',
    appId: '1:158681002300:ios:d3f671dfc2bd742fefee39',
    messagingSenderId: '158681002300',
    projectId: 'zinc-primer-455711-p7',
    storageBucket: 'zinc-primer-455711-p7.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR-2t5GssS3TtbkOdLhkhAPAnnotm0goY',
    appId: '1:158681002300:web:ce23ae181b30bbe6efee39',
    messagingSenderId: '158681002300',
    projectId: 'zinc-primer-455711-p7',
    authDomain: 'zinc-primer-455711-p7.firebaseapp.com',
    storageBucket: 'zinc-primer-455711-p7.firebasestorage.app',
    measurementId: 'G-8V034GZ9YS',
  );
}
